import { type Translations } from './types.ts';

export const DB_NAME = 'FaithJournalDB';
export const DB_VERSION = 1;
export const STORE_NAME = 'entries';

export const translations: Translations = {
  en: {
    appName: 'Faith Journal',
    dashboard: 'Dashboard',
    entries: 'Entries',
    settings: 'Settings',
    addNewEntry: 'Add New Entry',
    editEntry: 'Edit Entry',
    save: 'Save',
    cancel: 'Cancel',
    type: 'Type',
    testimony: 'Testimony',
    gratitude: 'Gratitude',
    prayerRequest: 'Prayer Request',
    date: 'Date',
    time: 'Time',
    personName: "Person's Name",
    title: 'Title (Optional)',
    details: 'Details',
    tags: 'Tags (comma-separated)',
    status: 'Status',
    pending: 'Pending',
    inProgress: 'In Progress',
    answered: 'Answered',
    allTypes: 'All Types',
    allStatuses: 'All Statuses',
    searchPlaceholder: 'Search by person, title, details, tags...',
    filter: 'Filter',
    exportToPDF: 'Export to PDF',
    noEntriesFound: 'No entries found. Add one to get started!',
    confirmDelete: 'Are you sure you want to delete this entry?',
    delete: 'Delete',
    edit: 'Edit',
    actions: 'Actions',
    entryDetails: 'Entry Details',
    close: 'Close',
    startDate: 'Start Date',
    endDate: 'End Date',
    filterByTags: 'Filter by Tags',
    tagsSelected: 'tags selected',
    // Reports
    summary: 'Summary',
    totalEntries: 'Total Entries',
    entriesByType: 'Entries by Type',
    prayerRequestsByStatus: 'Prayer Requests by Status',
    topPeople: 'Top People',
    recentAnsweredPrayers: 'Recently Answered Prayers',
    trendingTags: 'Trending Tags',
    // Settings
    language: 'Language',
    english: 'English',
    spanish: 'Spanish',
    appSettings: 'App Settings',
    dangerZone: 'Danger Zone',
    clearAllData: 'Clear All Data',
    clearAllDataWarning: 'This will permanently delete all entries. This action cannot be undone.',
    confirmClearAllData: 'Are you sure you want to delete ALL data?',
    dataCleared: 'All data has been cleared.',
    pdfReportTitle: 'Faith Journal Report',
    generatedOn: 'Generated on',
    // Date Filters
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    allTime: 'All Time',
  },
  es: {
    appName: 'Diario de Fe',
    dashboard: 'Tablero',
    entries: 'Entradas',
    settings: 'Ajustes',
    addNewEntry: 'Añadir Nueva Entrada',
    editEntry: 'Editar Entrada',
    save: 'Guardar',
    cancel: 'Cancelar',
    type: 'Tipo',
    testimony: 'Testimonio',
    gratitude: 'Gratitud',
    prayerRequest: 'Petición de Oración',
    date: 'Fecha',
    time: 'Hora',
    personName: 'Nombre de la Persona',
    title: 'Título (Opcional)',
    details: 'Detalles',
    tags: 'Etiquetas (separadas por coma)',
    status: 'Estado',
    pending: 'Pendiente',
    inProgress: 'En Progreso',
    answered: 'Respondida',
    allTypes: 'Todos los Tipos',
    allStatuses: 'Todos los Estados',
    searchPlaceholder: 'Buscar por persona, título, detalles, etiquetas...',
    filter: 'Filtrar',
    exportToPDF: 'Exportar a PDF',
    noEntriesFound: 'No se encontraron entradas. ¡Añade una para empezar!',
    confirmDelete: '¿Estás seguro de que quieres eliminar esta entrada?',
    delete: 'Eliminar',
    edit: 'Editar',
    actions: 'Acciones',
    entryDetails: 'Detalles de la Entrada',
    close: 'Cerrar',
    startDate: 'Fecha de Inicio',
    endDate: 'Fecha de Fin',
    filterByTags: 'Filtrar por Etiquetas',
    tagsSelected: 'etiquetas seleccionadas',
    // Reports
    summary: 'Resumen',
    totalEntries: 'Entradas Totales',
    entriesByType: 'Entradas por Tipo',
    prayerRequestsByStatus: 'Peticiones por Estado',
    topPeople: 'Personas Principales',
    recentAnsweredPrayers: 'Oraciones Respondidas Recientemente',
    trendingTags: 'Etiquetas Populares',
    // Settings
    language: 'Idioma',
    english: 'Inglés',
    spanish: 'Español',
    appSettings: 'Ajustes de la App',
    dangerZone: 'Zona de Peligro',
    clearAllData: 'Borrar Todos los Datos',
    clearAllDataWarning: 'Esto eliminará permanentemente todas las entradas. Esta acción no se puede deshacer.',
    confirmClearAllData: '¿Estás seguro de que quieres borrar TODOS los datos?',
    dataCleared: 'Todos los datos han sido borrados.',
    pdfReportTitle: 'Reporte del Diario de Fe',
    generatedOn: 'Generado el',
    // Date Filters
    today: 'Hoy',
    thisWeek: 'Esta Semana',
    thisMonth: 'Este Mes',
    allTime: 'Desde Siempre',
  },
